return {
    TOKEN = "XXX",
    CLIENT_SECRET = "XXX",
    TEST_CHANNEL = "XXX",
    SPOTIFY_CLIENT_ID = "XXX",
    SPOTIFY_CLIENT_SECRET = "XXX",
    CHATGPT_APIKEY = "XXX",
    GENIUS_APIKEY = "XXX",
    MAX_EMBED_REPLIES = 10
}
